import type { Incident, UserProfile, FamilyGroup, FamilyMember, FeedItem } from '../types';

export const MOCK_USER: UserProfile = {
  uid: 'mock-user-001',
  displayName: 'Eduardo Q.',
  email: 'eduardo@example.com',
  photoURL: null,
  reputation: 203750,
  level: 31,
  levelName: 'Guardian',
  levelIcon: '🛡️',
  isGuardian: true,
  isProbationary: false,
  totalReports: 1842,
  totalConfirmations: 5670,
  reportsToday: 7,
  dailyReportLimit: -1,
  isGhostMode: false,
  familyGroupIds: ['family-001'],
  kidProfileIds: ['kid-lucas-001'],
  chainIds: ['chain-demo-001'],
  createdAt: Date.now() - 365 * 86400000,
  lastActiveAt: Date.now(),
  verifiedIncidents: 312,
  removedIncidents: 45,
  mentees: 8,
};

export const MOCK_INCIDENTS: Incident[] = [
  {
    id: 'inc-001',
    reporterUid: 'user-002',
    reporterName: 'Maria Lima',
    reporterLevel: 8,
    reporterBadge: 'Sentinela de Bairro',
    category: 'robbery',
    severity: 'high',
    title: 'Attempted robbery near Maia train station',
    description: 'Two individuals on a motorcycle attempted to grab a phone from a pedestrian near the Maia station exit.',
    location: { latitude: 41.2356, longitude: -8.6200 },
    geohash: 'ez3q6yf1x',
    address: 'R. Dr. Carlos Felgueiras, Maia Centro',
    photoURLs: [],
    confirmCount: 12,
    denyCount: 1,
    credibilityScore: 18.5,
    status: 'active',
    isVerified: true,
    verifiedByUid: 'guardian-001',
    verifiedByName: 'Eduardo Q.',
    reactions: { useful: 45, beCareful: 23, watching: 67 },
    commentCount: 8,
    createdAt: Date.now() - 1200000,
    expiresAt: Date.now() + 85200000,
  },
  {
    id: 'inc-002',
    reporterUid: 'user-003',
    reporterName: 'João Costa',
    reporterLevel: 5,
    reporterBadge: 'Patrulheiro Local',
    category: 'accident',
    severity: 'medium',
    title: 'Car collision on Av. Visconde de Barreiros',
    description: 'Two vehicles collided at the roundabout. No serious injuries reported, but traffic is blocked.',
    location: { latitude: 41.2450, longitude: -8.6350 },
    geohash: 'ez3q6ybcz',
    address: 'Av. Visconde de Barreiros, Castêlo da Maia',
    photoURLs: [],
    confirmCount: 8,
    denyCount: 0,
    credibilityScore: 12.0,
    status: 'active',
    isVerified: false,
    verifiedByUid: null,
    reactions: { useful: 22, beCareful: 5, watching: 31 },
    commentCount: 3,
    createdAt: Date.now() - 2700000,
    expiresAt: Date.now() + 83700000,
  },
  {
    id: 'inc-003',
    reporterUid: 'user-004',
    reporterName: 'Ana Oliveira',
    reporterLevel: 15,
    reporterBadge: 'Escudo Popular',
    category: 'suspicious',
    severity: 'low',
    title: 'Suspicious person watching parked cars',
    description: 'A person has been walking around the parking lot looking inside cars for the last 30 minutes.',
    location: { latitude: 41.2250, longitude: -8.6080 },
    geohash: 'ez3q6yf3q',
    address: 'Zona Industrial da Maia, Águas Santas',
    photoURLs: [],
    confirmCount: 3,
    denyCount: 2,
    credibilityScore: 4.0,
    status: 'active',
    isVerified: false,
    verifiedByUid: null,
    reactions: { useful: 8, beCareful: 12, watching: 19 },
    commentCount: 5,
    createdAt: Date.now() - 5400000,
    expiresAt: Date.now() + 81000000,
  },
  {
    id: 'inc-004',
    reporterUid: 'user-005',
    reporterName: 'Carlos Melo',
    reporterLevel: 3,
    reporterBadge: 'Repórter de Rua',
    category: 'fire',
    severity: 'critical',
    title: 'Building fire on R. do Lidador',
    description: 'Visible flames and heavy smoke coming from a building. Bombeiros have been called.',
    location: { latitude: 41.2480, longitude: -8.6100 },
    geohash: 'ez3q6yb9z',
    address: 'R. do Lidador, Moreira da Maia',
    photoURLs: [],
    confirmCount: 25,
    denyCount: 0,
    credibilityScore: 42.0,
    status: 'active',
    isVerified: true,
    verifiedByUid: 'guardian-001',
    verifiedByName: 'Eduardo Q.',
    reactions: { useful: 89, beCareful: 67, watching: 120 },
    commentCount: 15,
    createdAt: Date.now() - 600000,
    expiresAt: Date.now() + 85800000,
  },
  {
    id: 'inc-005',
    reporterUid: 'user-006',
    reporterName: 'Lucia Ferreira',
    reporterLevel: 12,
    reporterBadge: 'Agente Comunitário',
    category: 'police',
    severity: 'medium',
    title: 'GNR checkpoint on EN13',
    description: 'GNR set up a checkpoint on the national road. Expect delays of approximately 20 minutes.',
    location: { latitude: 41.2180, longitude: -8.6380 },
    geohash: 'ez3q6yf6r',
    address: 'EN13, Pedrouços',
    photoURLs: [],
    confirmCount: 15,
    denyCount: 1,
    credibilityScore: 22.0,
    status: 'active',
    isVerified: false,
    verifiedByUid: null,
    reactions: { useful: 55, beCareful: 10, watching: 42 },
    commentCount: 7,
    createdAt: Date.now() - 3600000,
    expiresAt: Date.now() + 82800000,
  },
  {
    id: 'inc-006',
    reporterUid: 'mock-user-001',
    reporterName: 'Eduardo Q.',
    reporterLevel: 31,
    reporterBadge: 'Guardian',
    category: 'traffic',
    severity: 'low',
    title: 'Traffic jam near Maia Jardim',
    description: 'Heavy traffic due to road work near the shopping center. Use alternative routes.',
    location: { latitude: 41.2520, longitude: -8.6450 },
    geohash: 'ez3q6ybwx',
    address: 'Maia Jardim, Vermoim',
    photoURLs: [],
    confirmCount: 6,
    denyCount: 0,
    credibilityScore: 9.0,
    status: 'active',
    isVerified: false,
    verifiedByUid: null,
    reactions: { useful: 30, beCareful: 2, watching: 15 },
    commentCount: 2,
    createdAt: Date.now() - 7200000,
    expiresAt: Date.now() + 79200000,
  },
];

export const MOCK_FAMILY: FamilyGroup = {
  groupId: 'family-001',
  name: 'Querino Family',
  adminUid: 'mock-user-001',
  inviteCode: 'ATN3X8KP',
  memberCount: 4,
  maxMembers: 20,
  photoURL: null,
};

export const MOCK_FAMILY_MEMBERS: FamilyMember[] = [
  {
    uid: 'mock-user-001',
    displayName: 'Eduardo Q.',
    role: 'admin',
    locationSharingEnabled: true,
    location: { latitude: 41.2356, longitude: -8.6200 },
    isOnline: true,
    batteryLevel: 85,
  },
  {
    uid: 'family-member-002',
    displayName: 'Patricia Querino',
    role: 'member',
    locationSharingEnabled: true,
    location: { latitude: 41.2420, longitude: -8.6310 },
    isOnline: true,
    batteryLevel: 63,
  },
  {
    uid: 'family-member-003',
    displayName: 'Lucas Querino',
    role: 'kid',
    locationSharingEnabled: true,
    location: { latitude: 41.2290, longitude: -8.6120 },
    isOnline: true,
    batteryLevel: 72,
    isInSafeZone: true,
  },
  {
    uid: 'family-member-004',
    displayName: 'Sofia Querino',
    role: 'member',
    locationSharingEnabled: false,
    isOnline: false,
    batteryLevel: 14,
  },
];

export const MOCK_FEED: FeedItem[] = [
  {
    id: 'feed-001',
    type: 'incident_verified',
    actorName: 'Eduardo Q.',
    actorLevel: 31,
    summary: 'You verified the building fire on R. do Lidador as Guardian',
    createdAt: Date.now() - 300000,
  },
  {
    id: 'feed-002',
    type: 'new_incident',
    actorName: 'Maria Lima',
    actorLevel: 8,
    summary: 'Maria reported a robbery near Maia train station',
    createdAt: Date.now() - 1200000,
  },
  {
    id: 'feed-003',
    type: 'incident_verified',
    actorName: 'Guardian Torres',
    actorLevel: 31,
    summary: 'Guardian Torres verified the GNR checkpoint on EN13',
    createdAt: Date.now() - 1800000,
  },
  {
    id: 'feed-004',
    type: 'new_incident',
    actorName: 'Carlos Melo',
    actorLevel: 3,
    summary: 'Carlos reported a fire on R. do Lidador — awaiting verification',
    createdAt: Date.now() - 2400000,
  },
  {
    id: 'feed-005',
    type: 'user_leveled_up',
    actorName: 'João Costa',
    actorLevel: 5,
    summary: 'João reached Level 5 — Patrulheiro Local!',
    createdAt: Date.now() - 3600000,
  },
  {
    id: 'feed-006',
    type: 'new_incident',
    actorName: 'Ana Oliveira',
    actorLevel: 15,
    summary: 'Ana reported a suspicious person near Zona Industrial da Maia',
    createdAt: Date.now() - 5400000,
  },
  {
    id: 'feed-007',
    type: 'new_incident',
    actorName: 'Lucia Ferreira',
    actorLevel: 12,
    summary: 'Lucia reported a GNR checkpoint on EN13',
    createdAt: Date.now() - 7200000,
  },
  {
    id: 'feed-008',
    type: 'user_became_guardian',
    actorName: 'Renata Alves',
    actorLevel: 31,
    summary: 'Renata reached 200,000 pts and became a Guardian!',
    createdAt: Date.now() - 86400000,
  },
  {
    id: 'feed-009',
    type: 'user_leveled_up',
    actorName: 'Diego Martins',
    actorLevel: 20,
    summary: 'Diego reached Level 20 — Sentinela de Ouro! GuardScan 5km unlocked.',
    createdAt: Date.now() - 90000000,
  },
  {
    id: 'feed-010',
    type: 'incident_verified',
    actorName: 'Eduardo Q.',
    actorLevel: 31,
    summary: 'You removed a false robbery report near R. Dr. Carlos Felgueiras as Guardian',
    createdAt: Date.now() - 172800000,
  },
];

export function timeAgo(timestamp: number): string {
  const seconds = Math.floor((Date.now() - timestamp) / 1000);
  if (seconds < 60) return 'just now';
  const minutes = Math.floor(seconds / 60);
  if (minutes < 60) return `${minutes}m ago`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  return `${days}d ago`;
}

export function formatDistance(meters: number): string {
  if (meters < 1000) return `${Math.round(meters)}m`;
  return `${(meters / 1000).toFixed(1)}km`;
}
